### ISSUE TITLE
Make it "gogetable"

### ISSUE THREAD

**Issue by hgfischer** [ajensenwaud/gwitter#2]
It would be nice to be able to do ``go get github.com/ajensenwaud/gwitter`` just to install it. However, the file layout you chose make this impossible.

I recommend putting the pkg gwitter inside a subfolder and leave the main in the root folter of the repository, since its more likely that someone will use it as a cmd line software and not as a pkg.

I can do ``go get github.com/ajensenwaud/gwitter/cmd`` but the binary will be named ``cmd``.

**Comment by ajensenwaud** [comment]
Apollogies for the long waiting time -- the project has been revived and the feature has been implemented. You should now be able to 'go get' Gwitter as described above.
